#!/bin/sh
echo ">>>>>创建文件夹<<<<<<"
mkdir -p /Library/CRSettings/
# -R 0755 /Library/CRSettings/
#platform=$(uname -i)
#if [ $platform == "N71AP" || $platform == "N71mAP" ]; then #6s
cp -p /Library/PreferenceBundles/crsettings.bundle/Custom.png /Library/CRSettings/Custom.png
#fi
echo ">>>>>背景图片设置完成（6S）<<<<<<"
echo ">>>>> 其余设备请自行添加 <<<<<<"
exit 0
