#!/bin/sh
if [ -d /Library/CRSettings/ ]; then #如果目录存在
echo ">>>>>中文: 路径已存在<<<<<<"
echo ">>>>>English: Directory has already existed<<<<<<"
else
mkdir -p Library/CRSettings
fi
if [ -f /Library/CRSettings/Custom.png ]; then #如果文件存在
echo ">>>>>中文: 背景图片已存在<<<<<<"
echo ">>>>>English: Background photo has already existed<<<<<<"
else
platform=$(uname -i)
if [[ $platform == "N71AP" || $platform == "N71mAP" || $platform == "N61AP" ]]; then #6s and 6
cp -p /Library/PreferenceBundles/CRSettings.bundle/Custom47.png /Library/CRSettings/Custom.png
else
cp -p /Library/PreferenceBundles/CRSettings.bundle/Custom55.png /Library/CRSettings/Custom.png
fi
echo ">>>>>中文: 默认背景图片设置完成 <<<<<<"
echo ">>>>>English: Everything is set up<<<<<<"
fi
echo ">>>>>中文: 自定义背景图片请自行添加至以下路径 <<<<<<"
echo ">>>>> /Library/CRSettings/ <<<<<<"
echo ">>>>>English: Put an image which named as 'Custom.png' to /Library/CRSettings/ if you would like to customize.<<<<<<"
exit 0
